apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: docker-registry
  namespace: openchoreo-build-plane
spec:
  interval: 10m
  url: https://twuni.github.io/docker-registry.helm