apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: control-plane-gateway-tls
  namespace: openchoreo-control-plane
spec:
  secretName: control-plane-gateway-tls
  issuerRef:
    name: openchoreo-selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.openchoreo.localhost"