apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openchoreo-certs
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: gitops-openchoreo-deployment
  path: ./clusters/k3d-openchoreo/certs
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager