---
apiVersion: v1
kind: Namespace
metadata:
  name: openchoreo-build-plane
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openchoreo-build-plane
  namespace: openchoreo-build-plane
spec:
  interval: 10m
  timeout: 15m
  dependsOn:
    - name: openchoreo-control-plane
      namespace: openchoreo-control-plane
  chart:
    spec:
      chart: openchoreo-build-plane
      version: 0.0.0-latest-dev
      sourceRef:
        kind: HelmRepository
        name: openchoreo
        namespace: openchoreo-build-plane
  install:
    disableWait: true
    createNamespace: true
    disableHooks: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: openchoreo-build-plane-values
      valuesKey: values-bp.yaml
